import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import path from "node:path";

// Regenerates src/db/migrations-sql.ts with the FULL current schema DDL.
//
// We use `drizzle-kit export`, which derives the SQL from src/db/schema.ts (the
// same source `drizzle-kit push` uses) — NOT the drizzle/*.sql migration files,
// which are stale and missing tables. The embedded statements are what the
// one-time /api/admin/setup bootstrap runs to create the schema on a fresh
// database (e.g. a newly provisioned Turso DB), without needing the filesystem
// bundled into the serverless output.
//
// Run after changing the schema: `tsx scripts/embed-migrations.ts`.

const sql = execSync("drizzle-kit export --sql", {
  cwd: path.resolve("."),
  encoding: "utf8",
});

// The export emits plain DDL with statements terminated by `;`. None of the
// generated statements contain a semicolon outside that terminator, so a simple
// split is safe.
const statements = sql
  .split(";")
  .map((s) => s.trim())
  .filter((s) => s.length > 0);

const header =
  "// AUTO-GENERATED by scripts/embed-migrations.ts (drizzle-kit export). Do not edit by hand.\n" +
  "// Full current-schema DDL used by the one-time /api/admin/setup bootstrap to\n" +
  "// create the schema on a fresh database (e.g. a freshly provisioned Turso DB).\n\n" +
  `export const MIGRATION_STATEMENTS: string[] = ${JSON.stringify(statements, null, 2)};\n`;

writeFileSync(path.resolve("src/db/migrations-sql.ts"), header);
console.log(`Wrote src/db/migrations-sql.ts with ${statements.length} statements`);
